# Default values for db-migrate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mikejihbe/db-migrate-server
  tag: 0.1
  pullPolicy: Always
service:
  name: edp-db-migration-api
  type: ClusterIP
  port: 8080
resources: {}
